GET http://localhost:3001/todos HTTP/1.1

###

POST https://crud-silent-auction.herokuapp.com/BidItems/new
Content-Type: application/json

{
	"itemName": "Rainbow Heads",
	"img": "https://res.cloudinary.com/df5etts2d/image/upload/v1663688298/leeann-cline-I2RnOO8ojQ4-unsplash_egh3sj.jpg",
	"itemDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla est ullamcorper eget nulla facilisi etiam.\n\nQuis lectus nulla at volutpat diam ut venenatis tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tincidunt id aliquet risus feugiat. Tempus egestas sed sed risus. Sit amet purus gravida quis blandit turpis cursus.\n\nVel eros donec ac odio. Odio ut enim blandit volutpat maecenas. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas dui id ornare arcu odio ut sem nulla pharetra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus."
}

###


POST https://crud-silent-auction.herokuapp.com/BidItems/new
Content-Type: application/json

{
	"itemName": "Paint on Paper",
	"img": "https://res.cloudinary.com/df5etts2d/image/upload/v1664003024/IT%20Updates/sheldon-liu-FrQKfzoTgsw-unsplash_zmp31o.jpg",
	"itemDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla est ullamcorper eget nulla facilisi etiam.\n\nQuis lectus nulla at volutpat diam ut venenatis tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tincidunt id aliquet risus feugiat. Tempus egestas sed sed risus. Sit amet purus gravida quis blandit turpis cursus.\n\nVel eros donec ac odio. Odio ut enim blandit volutpat maecenas. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas dui id ornare arcu odio ut sem nulla pharetra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus."
}

###

POST https://crud-silent-auction.herokuapp.com/BidItems/new
Content-Type: application/json

{
	"itemName": "Mustard Hat",
	"img": "https://res.cloudinary.com/df5etts2d/image/upload/v1663688608/red-hat-factory-Di1Xvfyokpc-unsplash_i3kiwz.jpg",
	"itemDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla est ullamcorper eget nulla facilisi etiam.\n\nQuis lectus nulla at volutpat diam ut venenatis tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tincidunt id aliquet risus feugiat. Tempus egestas sed sed risus. Sit amet purus gravida quis blandit turpis cursus.\n\nVel eros donec ac odio. Odio ut enim blandit volutpat maecenas. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas dui id ornare arcu odio ut sem nulla pharetra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus."
}

###


POST https://crud-silent-auction.herokuapp.com/BidItems/new
Content-Type: application/json

{
	"itemName": "Pile of Rocks",
	"img": "https://res.cloudinary.com/df5etts2d/image/upload/v1663688297/nguyen-khiem-a3xJ--Wackk-unsplash_qrrdeg.jpg",
	"itemDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla est ullamcorper eget nulla facilisi etiam.\n\nQuis lectus nulla at volutpat diam ut venenatis tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tincidunt id aliquet risus feugiat. Tempus egestas sed sed risus. Sit amet purus gravida quis blandit turpis cursus.\n\nVel eros donec ac odio. Odio ut enim blandit volutpat maecenas. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas dui id ornare arcu odio ut sem nulla pharetra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus."
}

###


POST https://crud-silent-auction.herokuapp.com/BidItems/new
Content-Type: application/json

{
	"itemName": "Cool Art",
	"img": "https://res.cloudinary.com/df5etts2d/image/upload/v1663688298/robert-keane-rlbG0p_nQOU-unsplash_upq1nu.jpg",
	"itemDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla est ullamcorper eget nulla facilisi etiam.\n\nQuis lectus nulla at volutpat diam ut venenatis tellus. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Tincidunt id aliquet risus feugiat. Tempus egestas sed sed risus. Sit amet purus gravida quis blandit turpis cursus.\n\nVel eros donec ac odio. Odio ut enim blandit volutpat maecenas. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas dui id ornare arcu odio ut sem nulla pharetra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus."
}

###

POST http://localhost:3001/Bidder/new
Content-Type: application/json

{
	"name": "test",
	"bidAmount": 1,
	"bidItem": "KeyExample"
}

###

DELETE http://localhost:3001/todo/delete/6323435e27757f05ec9e0c7b

###

GET http://localhost:3001/todo/complete/60e585d86177f95ff0574323

###

PUT http://localhost:3001/BidItems/update/632db4219e81d8ca54a77227
Content-Type: application/json

{
	"bids": {"name": "Test", "bid": 300}
}